### ISSUE TITLE
Assignment 3 ready to be revised/graded

### ISSUE THREAD

**Issue by cristinadavila** [SES-5215-F2020/cdavilagonzalez-quant#3]
Hello! I've just uploaded the rmd and html files from assignment 3, for you to give them a look and grade them. the html file is also available for visualization here:

https://ses-5215-f2020.github.io/cdavilagonzalez-quant/Assignment-3.html

Hope you like them! Looking forward to your feedback.

with regards,

Cristina.

**Comment by c-voulgaris** [comment]
This looks nice. My only comment on your code is:

Line 18: Add `message=FALSE` to leave the column parsing messages from your knitted file.

And here are some comments on how you're interpretting your results - feel free to set a time in office hours to talk through this some more. 

Line 97: Your p-value is less than 0.05 and your 95-percent confidence interval does not include zero, so there is a statistically significant relationship. The width of the confidence interval doesn't matter, as long as it doesn't include zero.

Lines 146 to 161: The reason you're getting the message that the Chi-square approximation may inaccurate is that you have some cross-categories with zero values, but the reason for that is that those categories are mutually exclusive. For example, you have a categories for both variables for people who don't attend school. If the school enrollment variable says the person doesn't attend school, then the grade level variable will _not_ say they are attending 3rd grade - it will also say they don't attend school. So the issue here is that these variables are too closely related. I suggest filtering your dataset to only include people who attend school, at least for this one test.

Lines 163 - 176: Again, I would filter out the people who are younger than three years old, at least for this one test, the zero value for people under three with self-care difficulty is what's causing your test to fail (also - it's inaccurate - they may not have a disability, but kids under three totally have self-care difficulty, right?)

Again, the "approximations are subject to inaccuracy" isn't about how small the p-value or degrees of freedom are. It's because you have values in your observed table that are less than 5.
