### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by cristinadavila** [SES-5215-F2020/cdavilagonzalez-quant#4]
Hello! Files related to Assignment 4 have been uploaded and are currently ready for revision+grading. Hope you like them and thanks again for moving the deadline for this exercise :)

**Comment by saratepfer** [comment]
Nice job, Cristina! Please see a few comments below.

- Line 59: Note that it should be p-value < 0.05, not 0.5.
- rather than describing the relationships as inverse and proportional, I would describe them as positive and negative.
- line 61: I think you have the interpretation backwards here. You write, "When it comes income (PINCP), this variable has a slightly inverse relationship with the dependent variable, which indicates that as the age increases, the person’s total income decreases by an estimate of 0.00001791." it is not the income (the independent varialbe) that is decreasing; rather, it should be that, "A one-unit (or one-dollar) increase in the independent variable, income, is associated with a 0.00001791 unit decrease in age."
- Similarly, your interpretation of the categorical variable is backwards as well. Your model is showing that grandparents who are responsible for their grandchildren are approximately 3 years younger than those who are not.
