### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by cristinadavila** [SES-5215-F2020/cdavilagonzalez-quant#5]
Hello! Files related to Assignment 5 have been uploaded and are currently ready for revision+grading. Hope you like them  :)

available at:

https://ses-5215-f2020.github.io/cdavilagonzalez-quant/Assignment-5.html

**Comment by c-voulgaris** [comment]
Predicting age is tricky, since I'm assuming you aren't trying to suggest that any of your independent variables _cause_ differences in age. I'll be interested in seeing how you handle this in the final project.

One possibility would be to discuss this as a model predicting the age at which things happen - since two of your variables are likely to related to particular stages in life. People care for their grandchildren when they have young grandchildren. People develop self-care difficulties as they get older, and their income declines as they retire. If that's how you end up framing your analysis, you'd just consider sex as a control variable - since that's the one thing that doesn't typically change as someone ages. So your analysis would suggest that women generally enter these life stages about a year earlier than men.
